#!/bin/bash

#OAR -q abaca
#OAR -l {memcore>20000}/core=1,gpu=1,walltime=24:00:00
#OAR -p nodeset NOT IN (abacus27)
#OAR --stdout output/%jobname%.out
#OAR --stderr output/%jobname%.out

echo $@
source ~/.bashrc

conda activate py3.10_ml
export PYTHONUNBUFFERED=1
eval $@