#!/bin/bash

# Copyright © 2023 Paul Viallard <paul.viallard@gmail.com>
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.

# YOUR SLURM CONFIGURATION
# YOUR BATCH COMMANDS

echo $1
eval $1
